/**
 * Madde 9: 16×16 saf piksel art ikonlar. Her satır 16 karakter; her karakter 4-bit (16 renkli) VGA paletinden bir renk.
 * 32×32 görünüm aynı çizimin 2 kat, en yakın komşu büyütmesidir; yumuşatma yok.
 */
export const PALET: Record<string, string> = {
  k: '#000000',
  w: '#FFFFFF',
  g: '#C0C0C0',
  d: '#808080',
  n: '#000080',
  b: '#0000FF',
  t: '#008080',
  c: '#00FFFF',
  y: '#FFFF00',
  o: '#808000',
  r: '#FF0000',
  m: '#800000',
  G: '#008000',
  l: '#00FF00',
  p: '#800080',
  f: '#FF00FF',
}
export const PALET_AD: Record<string, string> = {
  k: 'siyah',
  w: 'beyaz',
  g: 'gümüş',
  d: 'gri',
  n: 'lacivert',
  b: 'mavi',
  t: 'turkuaz',
  c: 'camgöbeği',
  y: 'sarı',
  o: 'zeytin',
  r: 'kırmızı',
  m: 'bordo',
  G: 'yeşil',
  l: 'limon',
  p: 'mor',
  f: 'eflatun',
}

const BOS = '................'

const bilgisayar = [
  BOS,
  '.kkkkkkkkkkkkkk.',
  '.kggggggggggggk.',
  '.kgkkkkkkkkkkgk.',
  '.kgknnnnnnnnkgk.',
  '.kgkncnnnnnnkgk.',
  '.kgknnnnnnnnkgk.',
  '.kgknnnnnnnnkgk.',
  '.kgkkkkkkkkkkgk.',
  '.kggggggggggggk.',
  '.kgggggggggglgk.',
  '.kddddddddddddk.',
  '.kkkkkkkkkkkkkk.',
  '....kggggggk....',
  '..kkkkkkkkkkkk..',
  BOS,
]

export const IKONLAR = {
  bilgisayar,
  goruntu: bilgisayar.map((s, i) => (i >= 4 && i <= 7 ? '.kgkrryyGGbbkgk.' : s)),
  klasor: [
    BOS,
    BOS,
    '..kkkkk.........',
    '.kyyyyyk........',
    '.kyyyyyykkkkkkk.',
    '.kwwwwwwwwwwwyk.',
    '.kyyyyyyyyyyyyk.',
    '.kyyyyyyyyyyyok.',
    '.kyyyyyyyyyyyok.',
    '.kyyyyyyyyyyyok.',
    '.kyyyyyyyyyyyok.',
    '.kooooooooooook.',
    '.kkkkkkkkkkkkkk.',
    BOS,
    BOS,
    BOS,
  ],
  belge: [
    '..kkkkkkkkk.....',
    '..kwwwwwwwkk....',
    '..kwwwwwwwkwk...',
    '..kwwwwwwwkkkk..',
    '..kwwwwwwwwwwk..',
    '..kwdddddddwwk..',
    '..kwwwwwwwwwwk..',
    '..kwdddddwwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwddddddddwk..',
    '..kwwwwwwwwwwk..',
    '..kwdddddddwwk..',
    '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..',
    '..kkkkkkkkkkkk..',
    BOS,
  ],
  disket: [
    BOS,
    '.kkkkkkkkkkkkkk.',
    '.knnnggggggnnnk.',
    '.knnngkkgggnnnk.',
    '.knnngkkgggnnnk.',
    '.knnnggggggnnnk.',
    '.knnnnnnnnnnnnk.',
    '.knnnnnnnnnnnnk.',
    '.knnwwwwwwwwnnk.',
    '.knnwddddddwnnk.',
    '.knnwwwwwwwwnnk.',
    '.knnwddddwwwnnk.',
    '.knnwwwwwwwwnnk.',
    '.kkkkkkkkkkkkkk.',
    BOS,
    BOS,
  ],
  cop: [
    BOS,
    '....kkkkkkkk....',
    '...kwwwwwwwwk...',
    '..kkkkkkkkkkkk..',
    '..kwggggggggdk..',
    '...kwgdgdgdgdk..',
    '...kwgdgdgdgdk..',
    '...kwgdgdgdgdk..',
    '...kwgdgdgdgdk..',
    '...kwgdgdgdgdk..',
    '...kwgdgdgdgdk..',
    '...kwgdgdgdgdk..',
    '....kgggggggk...',
    '....kkkkkkkkk...',
    BOS,
    BOS,
  ],
  not: [
    BOS,
    '..kkkkkkkkkkkk..',
    '..knnnnnnnnnnk..',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwwk..',
    '..kwddddddddwk..',
    '..kwwwwwwwwwwk..',
    '..kwddddddddwk..',
    '..kwwwwwwwwwwk..',
    '..kwddddddwwwk..',
    '..kwwwwwwwwwwk..',
    '..kwddddddddwk..',
    '..kwwwwwwwwwwk..',
    '..kkkkkkkkkkkk..',
    BOS,
    BOS,
  ],
  oyun: [
    '......kkk.......',
    '.....krrrk......',
    '.....krwrk......',
    '.....krrrk......',
    '......kkk.......',
    '.......k........',
    '.......k........',
    '.......k........',
    '....kkkkkkk.....',
    '...kgggggggk....',
    '..kgwgggggggk...',
    '.kgrgggggggggk..',
    '.kgggggggggggdk.',
    '.kddddddddddddk.',
    '.kkkkkkkkkkkkkk.',
    BOS,
  ],
  mayin: [
    BOS,
    '.......k........',
    '.......k........',
    '...k.kkkkk.k....',
    '....kkkkkkk.....',
    '...kkwwkkkkk....',
    '...kkwwkkkkk....',
    '.kkkkkkkkkkkkk..',
    '...kkkkkkkkk....',
    '...kkkkkkkkk....',
    '....kkkkkkk.....',
    '...k.kkkkk.k....',
    '.......k........',
    '.......k........',
    BOS,
    BOS,
  ],
  bayrak: [
    BOS,
    BOS,
    '.....rrk........',
    '...rrrrk........',
    '.rrrrrrk........',
    '...rrrrk........',
    '.....rrk........',
    '.......k........',
    '.......k........',
    '.......k........',
    '.....kkkkk......',
    '...kkkkkkkkk....',
    BOS,
    BOS,
    BOS,
    BOS,
  ],
  uyari: [
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    '.....kykkyk.....',
    '....kyykkyyk....',
    '....kyykkyyk....',
    '...kyyykkyyyk...',
    '...kyyykkyyyk...',
    '..kyyyykkyyyyk..',
    '..kyyyyyyyyyyk..',
    '.kyyyyykkyyyyyk.',
    '.kyyyyykkyyyyyk.',
    'kyyyyyyyyyyyyyyk',
    'kkkkkkkkkkkkkkkk',
    BOS,
  ],
  bilgi: [
    '....kkkkkkkk....',
    '..kkwwwwwwwwkk..',
    '.kwwwwwbbwwwwwk.',
    '.kwwwwwbbwwwwwk.',
    'kwwwwwwwwwwwwwwk',
    'kwwwwwbbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    '.kwwwwwbbwwwwwk.',
    '.kwwwwbbbbwwwwk.',
    '..kkwwwwwwwwkk..',
    '....kkkwwkkk....',
    '......kwk.......',
    '.......k........',
    BOS,
  ],
  soru: [
    '....kkkkkkkk....',
    '..kkwwwwwwwwkk..',
    '.kwwwwbbbbwwwwk.',
    '.kwwwbbwwbbwwwk.',
    'kwwwwwwwwbbwwwwk',
    'kwwwwwwwbbwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwbbwwwwwwk',
    'kwwwwwwwwwwwwwwk',
    '.kwwwwwbbwwwwwk.',
    '.kwwwwwbbwwwwwk.',
    '..kkwwwwwwwwkk..',
    '....kkkwwkkk....',
    '......kwk.......',
    '.......k........',
    BOS,
  ],
  hata: [
    '.....kkkkkk.....',
    '...kkrrrrrrkk...',
    '..krrrrrrrrrrk..',
    '.krrwwrrrrwwrrk.',
    '.krrwwwrrwwwrrk.',
    'krrrrwwwwwwrrrrk',
    'krrrrrwwwwrrrrrk',
    'krrrrrwwwwrrrrrk',
    'krrrrwwwwwwrrrrk',
    '.krrwwwrrwwwrrk.',
    '.krrwwrrrrwwrrk.',
    '..krrrrrrrrrrk..',
    '...kkrrrrrrkk...',
    '.....kkkkkk.....',
    BOS,
    BOS,
  ],
  kumsaati: [
    '..kkkkkkkkkkkk..',
    '..kggggggggggk..',
    '..kkkkkkkkkkkk..',
    '...kwwwwwwwwk...',
    '...kwyyyyyywk...',
    '....kwyyyywk....',
    '.....kwyywk.....',
    '......kyyk......',
    '......kwyk......',
    '.....kwwywk.....',
    '....kwwwywwk....',
    '...kwwwyyywwk...',
    '...kwyyyyyywk...',
    '..kkkkkkkkkkkk..',
    '..kggggggggggk..',
    '..kkkkkkkkkkkk..',
  ],
  ag: [
    '.....kkkkkk.....',
    '...kkbbbbbbkk...',
    '..kbbbGGbbbbbk..',
    '.kbbGGGGbbbGbbk.',
    '.kbGGGGGbbGGbbk.',
    'kbbGGGGbbbGGGbbk',
    'kbbbGGbbbbGGGGbk',
    'kbbbbGbbbbbGGGbk',
    'kbbbbbbbbbbGGbbk',
    'kbbbbbGGbbbbbbbk',
    '.kbbbbGGGbbbbbk.',
    '.kbbbbbGGbbbbbk.',
    '..kbbbbbbbbbbk..',
    '...kkbbbbbbkk...',
    '.....kkkkkk.....',
    BOS,
  ],
  pencere: [
    BOS,
    '.kkkkkkkkkkkkkk.',
    '.knnnnnnnnnnnnk.',
    '.knnnnnnnnnnggk.',
    '.kkkkkkkkkkkkkk.',
    '.kggggggggggggk.',
    '.kgwwwwwwwwwwgk.',
    '.kgwwwwwwwwwwgk.',
    '.kgwwwwwwwwwwgk.',
    '.kgwwwwwwwwwwgk.',
    '.kgwwwwwwwwwwgk.',
    '.kggggggggggggk.',
    '.kkkkkkkkkkkkkk.',
    BOS,
    BOS,
    BOS,
  ],
  ampul: [
    '.....kkkkk......',
    '....kyyyyyk.....',
    '...kyywyyyyk....',
    '...kywyyyyyk....',
    '...kyyyyyyyk....',
    '...kyyyyyyyk....',
    '....kyyyyyk.....',
    '.....kyyyk......',
    '.....kdddk......',
    '.....kgggk......',
    '.....kdddk......',
    '......kkk.......',
    BOS,
    BOS,
    BOS,
    BOS,
  ],
  gulen: [
    '....kkkkkkkk....',
    '..kkyyyyyyyykk..',
    '.kyyyyyyyyyyyyk.',
    '.kyyyyyyyyyyyyk.',
    'kyyyykkyykkyyyyk',
    'kyyyykkyykkyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyykyyyyyyyykyyk',
    'kyyykyyyyyykyyyk',
    '.kyyykkkkkkyyyk.',
    '.kyyyyyyyyyyyyk.',
    '..kkyyyyyyyykk..',
    '....kkkkkkkk....',
    BOS,
    BOS,
  ],
  uzgun: [
    '....kkkkkkkk....',
    '..kkyyyyyyyykk..',
    '.kyyyyyyyyyyyyk.',
    '.kyyykyyyykyyyk.',
    'kyyyyykyykyyyyyk',
    'kyyyykyyyykyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyyyykkkkkkyyyyk',
    '.kyykyyyyyykyyk.',
    '.kyyyyyyyyyyyyk.',
    '..kkyyyyyyyykk..',
    '....kkkkkkkk....',
    BOS,
    BOS,
  ],
  havali: [
    '....kkkkkkkk....',
    '..kkyyyyyyyykk..',
    '.kyyyyyyyyyyyyk.',
    '.kkkkkkkkkkkkkk.',
    'kykkkkkkykkkkkyk',
    'kyykkkkyykkkkyyk',
    'kyyyyyyyyyyyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyykyyyyyyyykyyk',
    'kyyykyyyyyykyyyk',
    '.kyyykkkkkkyyyk.',
    '.kyyyyyyyyyyyyk.',
    '..kkyyyyyyyykk..',
    '....kkkkkkkk....',
    BOS,
    BOS,
  ],
} satisfies Record<string, string[]>

export type IkonAd = keyof typeof IKONLAR

/** Aynı renkteki yan yana pikseller tek dikdörtgen olur */
export function dikdortgenler(izgara: string[]) {
  const out: { x: number; y: number; w: number; renk: string }[] = []
  izgara.forEach((satir, y) => {
    let x = 0
    while (x < satir.length) {
      const ch = satir[x]
      let w = 1
      while (x + w < satir.length && satir[x + w] === ch) w++
      if (ch !== '.' && PALET[ch]) out.push({ x, y, w, renk: PALET[ch] })
      x += w
    }
  })
  return out
}

/** Madde 16: kum saati imleci. Aynı piksel çizim, 2 kat, SVG veri adresi */
export function imlecURL(ad: IkonAd = 'kumsaati', olcek = 2) {
  const r = dikdortgenler(IKONLAR[ad])
    .map((d) => `<rect x='${d.x}' y='${d.y}' width='${d.w}' height='1' fill='${d.renk}'/>`)
    .join('')
  const s = 16 * olcek
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${s}' height='${s}' viewBox='0 0 16 16' shape-rendering='crispEdges'>${r}</svg>`
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}") ${s / 2} ${s / 2}, wait`
}
